[server]
maxUploadSize = 200
enableXsrfProtection = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
fastRerenderThreshold = 1000

[client]
toolbarMode = "minimal"
showErrorDetails = false

[watcher]
usePolling = true 